### ISSUE TITLE
Get some pieces with multiple composers to test

### ISSUE THREAD

**Issue by blueNoteb5** [ELVIS-Project/simssadb#102]

**Comment by emilyhopkins** [comment]
Would multiple contributors of any kind work? Like librettist + composer? (I can't think of anything we have with two actual composers)

You could update these to include librettist since they're already in the old DB:
https://database.elvisproject.ca/search/?q=opera

(I can find you the librettists if you want to use these files, just let me know which.)

**Comment by blueNoteb5** [comment]
Actually both would be nice, having something with librettists but also some with more than one composer.

For two composers I was thinking of using some Beatles songs (most of them are Lennon and McCartney), but just to test, we wouldn't keep them in the database!

**Comment by emilyhopkins** [comment]
Oh of course you can test with whatever you like, just wanted to mention things we already had to save you making fake data or anything!

**Comment by blueNoteb5** [comment]
Awesome, I'll take a look at the librettists :)
