### ISSUE TITLE
Make search function more straight forward

### ISSUE THREAD

**Issue by juyaolongpaul** [ELVIS-Project/simssadb#144]
Now in the search bar, we can only search by music files, which means if we type `Mozart` and if there are no music files attached to `Mozart`, nothing will be returned, although we have `Mozart` entry as a person. We can develop a general search that the user can search for anything, and facet (advanced) search where we can search based on music files so we can do facet and feature search.

**Comment by emilyhopkins** [comment]
Do we actually want it to work this way? It should probably at least indicate that no files were found. I think returning a record = a file in our case. What would you actually return if they just searched for a composer we didn't have? Are you building separate composer pages that the user can view? (A musical work that has no files or only some of its files is a different case, I think.)

**Comment by juyaolongpaul** [comment]
I guess the main function of this DB is to return results based on music files, which makes a lot of sense. It just confuses me when I try to search for a composer in the DB and it will return nothing if there are no music files for that composer. @blueNoteb5 and I talked about this today, and we think we can develop a search bar in the list view of persons, so that we can search composers regardless of whether he/she has music files or not. But all in all, this is not a core functionality.

**Comment by emilyhopkins** [comment]
If you search a library catalogue for Octavia Butler and they don't have any of her books, why would you want the catalogue to return any results? What would it even return? You can search elsewhere if you want biographical information... maybe I'm missing something important, but here's one possibility:

Since we want to pre-load the composers from VIAF/some other source (so they can be in the DB with no files associated), we could have two possible error messages.

If we don't have files for Mozart, but we do have authority info for him, it could say:
"We don't have any files for Mozart yet! Would you like to [Upload some](link to upload page)"?

If we don't have files for Gubaidulina, and we also don't have authority info for her, it could say:
"We don't have that composer in our database! Would you like to [Upload files] and add them?"

(or something. I think that adding a composer should probably only be done through adding files, not just encouraging people to add composers as a separate thing)

**Comment by codaich** [comment]
I agree exactly with @emilyhopkins on this.

**Comment by juyaolongpaul** [comment]
Thank you for the suggestion @emilyhopkins , which makes a lot of sense. 

Initially, I had this question because I pre-filled the composers from Wikidata, and then the DB had thousands of person entires. Obviously, none of them are linked to any music files, so when I try to search the name of the composer, it returned nothing.  I was confused at the beginning, and now I understand why the DB is designed this way.
