### ISSUE TITLE
Nothing happens when I click submit on the update form

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/simssadb#183]
Maybe this is because you've disabled the login? But I can't test it as-is.

An important part of this form is what it requires for you to be able to submit a piece and if it validates that correctly.

**Comment by juyaolongpaul** [comment]
This is not implemented yet. Gustavo will work on the back-end to create all the instances once the upload form is submitted. Now, my focus is to design a functional upload page for users to input all the necessary information.

**Comment by emilyhopkins** [comment]
It's not a functional upload page if you can't submit anything! It's one thing if you won't have time to do it but this is definitely part of a "functional upload page!" :)

**Comment by juyaolongpaul** [comment]
Ah I see. Sorry about the confusion. This includes two parts of work: the front-end UI design and the back-end which deals with the input from the front-end. In this sense, it is not complete (what I mean is the front-end UI design), but since Gustavo is going to work on the back-end from Friday, and I will be continuously working on the front-end, this should be complete sometime at the end of this semester.

**Comment by blueNoteb5** [comment]
This is a duplicate issue so I'll close it.
