### ISSUE TITLE
Upload form formatting and mandatory fields

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/simssadb#219]
- [x] Text that you can access shouldn't be greyed out
- [ ] add asterisk for mandatory fields
- [x] composer before genres

**Comment by juyaolongpaul** [comment]
I am working on this issue right now as well. I can take care of the aesthetics of this page. Current tasks also include:

- [ ] Explain the `date` field (the two fields mean the starting date and the ending date). We need to specify the format of dates and add the corresponding validation schema
- [ ] The `Person` field also needs to be auto-completed
- [ ] The `Contributions` section should also have a minus button to remove the extra entries

The initial idea is to implement the aesthetics of the original uploading page like this:
![image](https://user-images.githubusercontent.com/9313094/56695001-142bb300-66b6-11e9-8051-672859508e13.png)
So that the title and the field are on the same line, which creates a cleaner looking. Anyways, we can talk about this as well tomorrow, and maybe we can draw a prototype layout of this page, so that I can work on it later.

**Comment by emilyhopkins** [comment]
Do we have a clear list of what fields are supposed to be mandatory? This came up a lot in the feedback (understandably...)

**Comment by juyaolongpaul** [comment]
In the newest version http://132.206.14.204:1337/en/, almost all the mandatory files are labelled, except for `Person Given Name`, and file field of the musical work on the second page. @blueNoteb5, could you work on these two things sometime? Thanks!

**Comment by emilyhopkins** [comment]
issue #264 addresses the dates thing in more detail based on user feedback
