### ISSUE TITLE
Set up django models

### ISSUE THREAD

**Issue by blueNoteb5** [ELVIS-Project/simssadb#25]

**Comment by ahankinson** [comment]
You might find it useful to separate out your models into different files, instead of keeping them all in one big models file. Have a look at https://github.com/diamm/diamm/tree/master/diamm/models/data

A few implementation notes:
 - You will need to ensure your models get imported on startup by importing them in `models/__init__.py`. See: https://github.com/diamm/diamm/blob/master/diamm/models/__init__.py
 - You should register your models to an app and give them an `app_label`: https://github.com/diamm/diamm/blob/master/diamm/models/data/archive.py#L9-L10
 - You can separate out your signals into their own files too: https://github.com/diamm/diamm/tree/master/diamm/signals
 - You can trigger your signals to register themselves when your app is fully booted. To do this you need to create an app class and import them when your app automatically calls the ready method: https://github.com/diamm/diamm/blob/master/diamm/diamm_data/apps.py

**Comment by blueNoteb5** [comment]
Thanks for the feedback and advice, @ahankinson!

I'll take a good look at the DIAMM code base to see how I should do things in Django
