### ISSUE TITLE
Make it possible to undo selections in Upload form

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/simssadb#265]
Maybe this issue was because the work/section upload wasn't working at the time? If it's already resolved please mark as closed.

Note from Ian: There has to be a way to de-select a piece if you accidentally choose the wrong one: in the upload stage, I found that I had accidentally uploaded the Mass section as a whole work instead of placing it in the "section" portion of the document. There is no way to de-select cancel this unless you reload the page or go back to the previous page.

**Comment by juyaolongpaul** [comment]
This should be easy to fix, mostly using a different widget (or configure the current one) for file uploading so that it can have a `cancel` button of some sort. 

BTW, I will go through all the issues @emilyhopkins created, and classify the priority of them. For optional ones, I will label them as `enhancement` since they are not deal breakers, and for real deal breakers that we need to try finishing as much as possible, I will label them as `core`.
