### ISSUE TITLE
Date of composition in some musical work does not seem right

### ISSUE THREAD

**Issue by juyaolongpaul** [ELVIS-Project/simssadb#94]
#88

**Comment by emilyhopkins** [comment]
Two things:

1) The default list of pieces maybe doesn't need to show the dates, or should only show them if the pieces are being searched by date? The default list could be composer and title only.

2) Maybe we should use the composer's dates in the back end to allow the piece to be searched by date, but not actually display them as composition dates. So "composition date" would be blank, since it's unknown, but the composer's dates could be used in the back end so that a search for pieces from, e.g., 1500-1550 would still return this composer's works.

**Comment by julieemelyncumming** [comment]
Sounds good!  Julie

Julie E. Cumming
Schulich School of Music, McGill University
555 Sherbrooke St. West
Montreal, Quebec H3A 1E3 Canada
Wirth Music Building, Room A 628; 514-398-4400 x00313
julie.cumming@mcgill.ca<mailto:julie.cumming@mcgill.ca>

**Comment by emilyhopkins** [comment]
Investigate current behaviour before demo to make sure we don't embarass ourselves!
